CAB-4418 implement and test employee typeahead
uw-it-edm/docfinity-services pull request #43
Opened 2021-09-16 16:27 UTC by jfshenuw

This is the first part and includes the implementation and unit test.  A later PR will include documentation and e2e test.

2021-09-17 17:24 UTC, farmas commented on src/main/java/edu/uw/edm/docfinity/config/AppConfig.java
> +        if (StringUtils.isEmpty(appProperties.getKeystoreLocation())) {
This method is marked as deprecated.

2021-09-17 17:24 UTC, farmas commented on src/main/java/edu/uw/edm/docfinity/config/AppConfig.java
> +/** @author Jay Shen */
I don't believe the original author is required, we can always look at git history.

2021-09-17 17:25 UTC, farmas commented on src/main/java/edu/uw/edm/docfinity/config/AppConfig.java
> +            throws KeyStoreException, FileNotFoundException, IOException, CertificateException,
Would it be easier to just declare the base Exception instead of enumerating each individual type?

2021-09-17 17:27 UTC, farmas commented on src/main/java/edu/uw/edm/docfinity/config/AppConfig.java
> +            //            trustManagers[0] = new AuthorizeEverybodyTrustManager();
Please remove.

2021-09-17 17:28 UTC, farmas commented on src/main/java/edu/uw/edm/docfinity/config/AppConfig.java
> +        KeyManager[] keyManagers = getKeyManagers(appProperties);
getKeyManagers can return null, does that need to be handled here?

2021-09-17 17:30 UTC, farmas commented on src/main/java/edu/uw/edm/docfinity/config/AppConfig.java
> +                                request.removeHeaders(HTTP.TRANSFER_ENCODING);
Could you explain why these headers need to be removed?

2021-09-17 20:19 UTC, jfshenuw commented on src/main/java/edu/uw/edm/docfinity/config/AppConfig.java
> +        if (StringUtils.isEmpty(appProperties.getKeystoreLocation())) {
good catch. change "StringUtils.isEmpty()" to "ObjectUtils.isEmpty()"

2021-09-17 20:19 UTC, jfshenuw commented on src/main/java/edu/uw/edm/docfinity/config/AppConfig.java
> +/** @author Jay Shen */
deleted author from all files.

2021-09-17 20:24 UTC, jfshenuw commented on src/main/java/edu/uw/edm/docfinity/config/AppConfig.java
> +            throws KeyStoreException, FileNotFoundException, IOException, CertificateException,
Yes, I did that for remaining methods. I listed the exceptions once to let us know the kind of exceptions it may throw. I think it is a good balance between always listing all exceptions and always listing base exceptions.

2021-09-17 20:29 UTC, jfshenuw commented on src/main/java/edu/uw/edm/docfinity/config/AppConfig.java
> +            //            trustManagers[0] = new AuthorizeEverybodyTrustManager();
removed commented out code.

2021-09-17 20:36 UTC, farmas commented on src/main/java/edu/uw/edm/docfinity/properties/AppProperties.java
> +public class AppProperties {
Could you add developer comments to each of these properties? We are trying to keep the Properties files fully documented.

2021-09-17 20:39 UTC, farmas commented on src/main/java/edu/uw/edm/docfinity/service/PersonService.java
> +public interface PersonService {
Could you add developer comments to each interface method to clarify intent? We are trying to standardize interfaces to be fully documented.

2021-09-17 20:39 UTC, jfshenuw commented on src/main/java/edu/uw/edm/docfinity/config/AppConfig.java
> +        KeyManager[] keyManagers = getKeyManagers(appProperties);
No. It is passed to SSLContext.init and null is a legitimate value. See 
https://docs.oracle.com/javase/8/docs/api/javax/net/ssl/SSLContext.html for detail.

2021-09-17 20:40 UTC, farmas commented on src/main/java/edu/uw/edm/docfinity/service/PersonService.java
> +/** @author Jay Shen */
Please remove.

2021-09-17 20:44 UTC, farmas commented on src/test/java/edu/uw/edm/docfinity/v1/controller/EmployeeControllerTest.java
> +// use "@SpringBootTest" to start a local test server
What are these comments meant to be used? I don't think the expectation is for a developer to uncomment lines in order to run tests, otherwise, how are they going to run on CI?

2021-09-17 20:47 UTC, farmas commented on src/test/java/edu/uw/edm/docfinity/v1/controller/EmployeeControllerTest.java
> +    public void testGetEmployeeByEmployeeIdPreferredNamepPeferredNameWithId() throws Exception {
Small typo on test name.

2021-09-17 20:48 UTC, farmas commented on src/test/java/edu/uw/edm/docfinity/v1/controller/EmployeeControllerTest.java
> +    public static final String CONTEXT_PATH = "";
What is this context path for? It doesn't seem to ever bet set.

2021-09-17 20:58 UTC, farmas commented on src/main/java/edu/uw/edm/docfinity/v1/controller/EmployeeController.java
> +    @RequestMapping(method = RequestMethod.GET, value = "{regId}")
Looking at the unit tests, this seems to be either regId or employeeId?

2021-09-17 20:58 UTC, farmas commented on src/main/java/edu/uw/edm/docfinity/v1/controller/EmployeeController.java
> +    public ResponseEntity<EmployeeDTO> read(
Add dev comments to make it clear what in the intent of each of the parameters and their valid values.

2021-09-17 20:58 UTC, farmas commented on src/main/java/edu/uw/edm/docfinity/v1/controller/EmployeeController.java
> +                    String displayNameFormat) {
Should this be an Enum?

2021-09-17 20:59 UTC, farmas commented on src/main/java/edu/uw/edm/docfinity/v1/controller/EmployeeController.java
> +        log.trace("read(regId=" + regId + ", displayNameFormat=" + displayNameFormat + ")");
regId or employeeId?

2021-09-17 21:03 UTC, farmas commented on src/main/java/edu/uw/edm/docfinity/v1/controller/EmployeeController.java
> +                sc = HttpStatus.resolve(Integer.parseInt(error.getStatusCode()));
For my own understanding, what is this meant to accomplish?

2021-09-17 21:04 UTC, farmas commented on src/main/java/edu/uw/edm/docfinity/v1/controller/EmployeeController.java
> +    public ResponseEntity<Page<EmployeeDTO>> search(
Add dev comments that describe what is the expectation of the query format.

2021-09-17 21:06 UTC, jfshenuw commented on src/main/java/edu/uw/edm/docfinity/config/AppConfig.java
> +                                request.removeHeaders(HTTP.TRANSFER_ENCODING);
All our existing APIs have this code. So I kept it.  Apache HTTP may add "Transfer-Encoding: chunked" but some web services, e.g. PWS,  may not support "chunked" mode.

2021-09-17 21:07 UTC, farmas commented on src/main/java/edu/uw/edm/docfinity/v1/controller/EmployeeController.java
> +            log.trace(
Consider using the {} syntax so that the string(s) are not built unless tracing is enabled. Same for the other uses of log.trace() in this file.

2021-09-17 21:11 UTC, farmas commented on src/main/java/edu/uw/edm/docfinity/v1/controller/EmployeeController.java
> +        } else if (trimmedQuery.indexOf(',') != -1) { // format: lastName, firstName
What happens if the person has multiple last names or multiple first names?

2021-09-17 21:13 UTC, farmas commented on src/main/java/edu/uw/edm/docfinity/v1/controller/EmployeeController.java
> +                builder.employeeID(trimmedQuery.substring(startIdx + 1, endIdx));
What happens if the builder ends up not setting the employeeID? Is the request still going to happen? I would assume that if no property is able to be set we wouldn't contact PWS.

2021-09-17 21:13 UTC, farmas commented on src/main/java/edu/uw/edm/docfinity/v1/controller/EmployeeController.java
> +        PersonSearchModel ret = builder.build();
What happens if the query format is wrong? I would expect this API to return in error to alert us that an invalid input has been provided.

2021-09-17 21:16 UTC, farmas commented on src/main/java/edu/uw/edm/docfinity/v1/controller/EmployeeController.java
> +        builder.employeeId(employeeId).uwNetId(person.getUWNetID()).uwRegId(person.getUWRegID());
What happens if the employeeId ends up being empty string here? Should that be considered an error that we need to be alerted?

2021-09-17 21:17 UTC, jfshenuw commented on src/main/java/edu/uw/edm/docfinity/v1/controller/EmployeeController.java
> +    @RequestMapping(method = RequestMethod.GET, value = "{regId}")
No expected use case at present. I found during testing that PWS would accept employee ID as well. I may remove the unit test with employee ID to avoid confusion.

2021-09-17 21:17 UTC, farmas commented on src/main/java/edu/uw/edm/docfinity/v1/controller/EmployeeController.java
> +        String displayName = surname + "," + firstName + (middleName == null ? "" : " " + middleName);
I think there needs to be a space after the ","

2021-09-17 21:20 UTC, jfshenuw commented on src/main/java/edu/uw/edm/docfinity/v1/controller/EmployeeController.java
> +                    String displayNameFormat) {
Either String or enum would work. I prefer String, as I don't need to introduce an enum.

2021-09-17 21:21 UTC, jfshenuw commented on src/main/java/edu/uw/edm/docfinity/v1/controller/EmployeeController.java
> +        log.trace("read(regId=" + regId + ", displayNameFormat=" + displayNameFormat + ")");
we expect regId here.

2021-09-17 21:25 UTC, farmas commented
Future items to be logged as Jiras:
- Fail fast when contacting external service. If PWS doesn't return a response in 5 seconds (configurable), the service should return an error message to DocFinity. There could be a different setting for get and search.
- How to handle truncation, if the search returns more items that the page size, it could add a last item to the list to alert the user that there are more results than what are displayed in the list.

2021-09-17 21:27 UTC, jfshenuw commented on src/main/java/edu/uw/edm/docfinity/v1/controller/EmployeeController.java
> +                sc = HttpStatus.resolve(Integer.parseInt(error.getStatusCode()));
map PWS status code (string) to HttpStatus for return to client. better error message to client. I added a comment to the code.

2021-09-17 21:39 UTC, jfshenuw commented on src/main/java/edu/uw/edm/docfinity/v1/controller/EmployeeController.java
> +    public ResponseEntity<Page<EmployeeDTO>> search(
added a comment on supported format.

2021-09-17 21:42 UTC, jfshenuw commented on src/main/java/edu/uw/edm/docfinity/v1/controller/EmployeeController.java
> +        } else if (trimmedQuery.indexOf(',') != -1) { // format: lastName, firstName
did you mean multiple words?

2021-09-17 21:45 UTC, jfshenuw commented on src/main/java/edu/uw/edm/docfinity/v1/controller/EmployeeController.java
> +        builder.employeeId(employeeId).uwNetId(person.getUWNetID()).uwRegId(person.getUWRegID());
It would return an empty string to the client.  It should not happen, unless there is a data error in PWS.

2021-09-17 21:47 UTC, jfshenuw commented on src/main/java/edu/uw/edm/docfinity/v1/controller/EmployeeController.java
> +        String displayName = surname + "," + firstName + (middleName == null ? "" : " " + middleName);
I checked UUI and it has a space. So a space is added. Good catch.

2021-09-17 21:55 UTC, jfshenuw commented on src/main/java/edu/uw/edm/docfinity/v1/controller/EmployeeController.java
> +                builder.employeeID(trimmedQuery.substring(startIdx + 1, endIdx));
This is to accommodate a special use case and the "lastName, firstName (employeeID)" is entered by end users.

2021-09-17 22:01 UTC, jfshenuw commented on src/main/java/edu/uw/edm/docfinity/v1/controller/EmployeeController.java
> +    public ResponseEntity<EmployeeDTO> read(
listed valid values of displayNameFormat

2021-09-17 22:03 UTC, jfshenuw commented on src/main/java/edu/uw/edm/docfinity/v1/controller/EmployeeController.java
> +        log.trace("read(regId=" + regId + ", displayNameFormat=" + displayNameFormat + ")");
I think PWS would take regId, employeeId, studentId or netId.

2021-09-17 22:07 UTC, jfshenuw commented on src/main/java/edu/uw/edm/docfinity/properties/AppProperties.java
> +public class AppProperties {
If the names include the intent already, additional comments may be redundant.

2021-09-17 22:08 UTC, jfshenuw commented on src/main/java/edu/uw/edm/docfinity/service/PersonService.java
> +public interface PersonService {
If the names include the intent already, additional comments may be redundant.

2021-09-17 22:08 UTC, jfshenuw commented on src/main/java/edu/uw/edm/docfinity/service/PersonService.java
> +/** @author Jay Shen */
deleted

2021-09-17 22:11 UTC, jfshenuw commented on src/test/java/edu/uw/edm/docfinity/v1/controller/EmployeeControllerTest.java
> +// use "@SpringBootTest" to start a local test server
Useful info to understand the subtle difference between the annotations.

2021-09-17 22:17 UTC, jfshenuw commented on src/main/java/edu/uw/edm/docfinity/v1/controller/EmployeeController.java
> +        PersonSearchModel ret = builder.build();
I don't want to get into all possible invalid formats. Users could switch firstName and lastName, and enter special characters by mistake.

2021-09-17 22:28 UTC, jfshenuw commented on src/main/java/edu/uw/edm/docfinity/v1/controller/EmployeeController.java
> +            log.trace(
good idea!

2021-09-17 22:32 UTC, jfshenuw commented on src/test/java/edu/uw/edm/docfinity/v1/controller/EmployeeControllerTest.java
> +    public static final String CONTEXT_PATH = "";
empty context is used here. It would be easier to change in case we need to test other context.

2021-09-17 22:35 UTC, jfshenuw commented on src/test/java/edu/uw/edm/docfinity/v1/controller/EmployeeControllerTest.java
> +    public void testGetEmployeeByEmployeeIdPreferredNamepPeferredNameWithId() throws Exception {
fixed. thank you for catching this.

2021-09-17 23:56 UTC, jfshenuw commented on src/main/java/edu/uw/edm/docfinity/service/PersonService.java
> +public interface PersonService {
changed findOneByRegId to getPersonbyId, which is better name. I added comments that the Id may one of regId, netId, employeeId, or a studentId

2021-09-21 21:24 UTC, farmas commented on src/main/java/edu/uw/edm/docfinity/config/AppConfig.java
> +        KeyManager[] keyManagers = getKeyManagers(appProperties);
What happens if the paremeter is null? Is it expected to work or is it going to fail down the line with some cryptic error message? If it is required for the regular operations maybe we should throw a descriptive error.

2021-09-21 21:27 UTC, farmas commented on src/main/java/edu/uw/edm/docfinity/properties/AppProperties.java
> +public class AppProperties {
Having a standard makes it easy to follow for all properties, if nothing has comments then it sets the precedent that no property should be documented. Additionally, what may be obvious to one developer might not be obvious to another.

2021-09-21 21:29 UTC, farmas commented on src/main/java/edu/uw/edm/docfinity/v1/controller/EmployeeController.java
> +                    String displayNameFormat) {
When there is a limited set of valid values I would think Enum has advantages. Up to you.

2021-09-21 21:35 UTC, farmas commented on src/main/java/edu/uw/edm/docfinity/v1/controller/EmployeeController.java
> +                builder.employeeID(trimmedQuery.substring(startIdx + 1, endIdx));
But still, if this "if" statement is missed the builder will have no parameter... shouldn't we stop the request from going through?

2021-09-21 21:37 UTC, farmas commented on src/main/java/edu/uw/edm/docfinity/v1/controller/EmployeeController.java
> +        } else if (trimmedQuery.indexOf(',') != -1) { // format: lastName, firstName
Yes, like if my name is "Federico Silva Armas" how would it know that "Silva" is the start of my last name or if it is my middle name?

2021-09-21 22:06 UTC, jfshenuw commented on src/main/java/edu/uw/edm/docfinity/properties/AppProperties.java
> +public class AppProperties {
I checked a few of our existing APIs, they don't have additional comments.  We may need to define a standard first. I really don't think extra comments are beneficial, when the names convey the intent already.  Take "keystoreLocation" as an example, a comment like "the location of the keystore" does not add any value.

2021-09-21 22:12 UTC, jfshenuw commented on src/main/java/edu/uw/edm/docfinity/v1/controller/EmployeeController.java
> +        } else if (trimmedQuery.indexOf(',') != -1) { // format: lastName, firstName
Without a dictionary, I would not know how to split the name into last name and first name. I followed our existing logic in the UUI, which may split the names incorrectly sometimes. Please let me know if you have good way to figure multiword names.

2021-09-21 22:24 UTC, jfshenuw commented on src/main/java/edu/uw/edm/docfinity/v1/controller/EmployeeController.java
> +                builder.employeeID(trimmedQuery.substring(startIdx + 1, endIdx));
We could. This is a special case. It is possible to move this logic to "getEmployeeById" later. For now, I'd like to avoid handling the unlikely use case of having an empty "()".

2021-09-22 00:04 UTC, farmas commented on src/main/java/edu/uw/edm/docfinity/v1/controller/EmployeeController.java
> +    @RequestMapping(method = RequestMethod.GET, value = "{regId}")
Yes, could you remove the unit test? Especially if all across the board it is referenced as "regId", I wouldn't expect the contract to also accept a "employeeId".

2021-09-22 00:05 UTC, farmas commented on src/main/java/edu/uw/edm/docfinity/v1/controller/EmployeeController.java
> +        log.trace("read(regId=" + regId + ", displayNameFormat=" + displayNameFormat + ")");
I think my confusion here is that the unit test implies that this method supports both, I would say to remove the unit test.

2021-09-22 00:08 UTC, farmas requested changes
For the dev comments, could you follow the javadoc style? Something like:
```
/**
*
* @param  
* @param  name the location of the image, relative to the url argument
*/
```
I believe that is the standard no?

2021-09-22 04:47 UTC, farmas commented on src/main/java/edu/uw/edm/docfinity/v1/controller/EmployeeController.java
> +        return ret;
I still think that if the builder didn't set any property we should not call PWS.

2021-09-22 04:48 UTC, farmas commented on src/main/java/edu/uw/edm/docfinity/v1/controller/EmployeeController.java
> +                builder.employeeID(trimmedQuery.substring(startIdx + 1, endIdx));
I think it is fine to leave the edge cases unhandled here, as long as we are not contacting PWS when no parameters are set.

2021-09-22 04:49 UTC, farmas commented on src/main/java/edu/uw/edm/docfinity/v1/controller/EmployeeController.java
> +        builder.employeeId(employeeId).uwNetId(person.getUWNetID()).uwRegId(person.getUWRegID());
I see, in that case consider setting the default value to "N/A" instead of empty string.

2021-09-22 23:36 UTC, jfshenuw commented on src/main/java/edu/uw/edm/docfinity/v1/controller/EmployeeController.java
> +        builder.employeeId(employeeId).uwNetId(person.getUWNetID()).uwRegId(person.getUWRegID());
I don't agree, as I don't think it is a good idea to change the value from PWS. If PWS returns an empty string, we should pass that along, instead of transforming it.

2021-09-22 23:43 UTC, jfshenuw commented on src/main/java/edu/uw/edm/docfinity/v1/controller/EmployeeController.java
> +                builder.employeeID(trimmedQuery.substring(startIdx + 1, endIdx));
Okay, I will return a bad request in case the query is empty.

2021-09-22 23:44 UTC, jfshenuw commented on src/main/java/edu/uw/edm/docfinity/v1/controller/EmployeeController.java
> +        log.trace("read(regId=" + regId + ", displayNameFormat=" + displayNameFormat + ")");
I already removed the extra unit test, which created the confusion.

2021-09-22 23:45 UTC, jfshenuw commented on src/main/java/edu/uw/edm/docfinity/v1/controller/EmployeeController.java
> +                    String displayNameFormat) {
I still prefer strings, which is simpler.

2021-09-22 23:46 UTC, jfshenuw commented on src/main/java/edu/uw/edm/docfinity/v1/controller/EmployeeController.java
> +    @RequestMapping(method = RequestMethod.GET, value = "{regId}")
the unit test was removed already.

2021-09-22 23:58 UTC, jfshenuw commented on src/main/java/edu/uw/edm/docfinity/config/AppConfig.java
> +        KeyManager[] keyManagers = getKeyManagers(appProperties);
I spent hours to look into this and to test different cases. Here is what I found:
* keyManagers is null for unit tests, unless we create a fake, valid java keystore for unit tests. I don't like the complication of creating such a fake java keystore just for unit tests. 
* When the keyManagers was null, it was treated the same as no client cert and PWS returned an error response.

I don't think we need to worry about null values, because all our other APIs are handling it the same way and we have not experienced any issues for many years. This does not mean it would never happen, but we don't need to complicate our code to handle such an unlikely case.  What is much more likely could be an expired cert (I hope you are not going to ask me to check the cert validity at this point)?

2021-09-23 00:01 UTC, jfshenuw commented on src/main/java/edu/uw/edm/docfinity/v1/controller/EmployeeController.java
> +        return ret;
ok, I will add the optimization.

2021-09-23 00:10 UTC, jfshenuw commented
> For the dev comments, could you follow the javadoc style? Something like:
> 
> ```
> /**
> *
> * @param  
> * @param 
> */
> ```
> 
> I believe that is the standard no?

They are usually added to public APIs, if javadoc is going to be generated.  A good example would be public APIs in pws-client.  The generated java doc can then be used by pws-client users. For dev comments, I would use regular comments, if necessary.

2021-09-23 00:27 UTC, farmas commented on src/main/java/edu/uw/edm/docfinity/config/AppConfig.java
> +        KeyManager[] keyManagers = getKeyManagers(appProperties);
If the error message from PWS is descriptive as you said we should be ok.

2021-09-23 04:11 UTC, farmas approved these changes

2021-09-27 17:26 UTC, merged